const SUPPORTED = { ucp: new Set(['ucp-current-m1']), ap2: new Set(['ap2-v0.2-m1']) };
const PRECEDENCE = { PASS: 0, WARN: 1, UNKNOWN: 2, BLOCK: 3 };
function result(invariant_id,status,reason_code,message,unknown_reason=null,details={}) { return {invariant_id,status,unknown_reason,reason_code,message,evidence_ids:[],details}; }
function findObject(f,n,t){ return (f.objects||[]).find(o=>o?.source?.namespace===n&&o?.source?.object_type===t)||null; }
function unsupportedVersion(objects){ for(const o of objects.filter(Boolean)){const s=SUPPORTED[o.source?.namespace];if(!s||!s.has(o.source?.protocol_version))return o;}return null; }
function authoritativeTotal(c){const t=c?.raw?.totals;if(!Array.isArray(t))return null;const m=t.filter(x=>x?.type==='total'&&Number.isInteger(x?.amount));return m.length===1?m[0].amount:null;}
function declaredTransformation(f){const c=f?.context||{};return c.declared_transformation||c.transformation||c.payment_transformation||c.fx||null;}
function exactState(c,p){if(!c)return result('TP-CX-003','UNKNOWN','EXACT_AUTHORIZED_STATE_MISSING','Referenced UCP checkout artifact is unavailable.','MISSING_OBJECT');if(!p)return result('TP-CX-003','UNKNOWN','PAYMENT_MANDATE_MISSING','AP2 payment mandate is unavailable.','MISSING_OBJECT');const u=unsupportedVersion([c,p]);if(u)return result('TP-CX-003','UNKNOWN','UNSUPPORTED_PROTOCOL_VERSION',`Unsupported ${u.source.namespace} profile ${u.source.protocol_version}.`,'UNSUPPORTED_VERSION');const tx=p.raw?.transaction_id;if(!tx)return result('TP-CX-003','UNKNOWN','EXACT_STATE_BINDING_MISSING','Payment mandate does not provide the exact-state binding reference.','MISSING_EVIDENCE');return result('TP-CX-003','PASS','EXACT_AUTHORIZED_STATE_ESTABLISHED','Exact authorized checkout state relation is available for evaluation.',null,{transaction_id:tx,checkout_external_id:c.external_id??null});}
function dependentUnknown(id,pre,message){return result(id,'UNKNOWN','PREREQUISITE_NOT_PROVEN',message,pre.unknown_reason||'MISSING_EVIDENCE');}
function currencyProjection(f,c,p,pre){if(pre.status!=='PASS')return dependentUnknown('TP-CX-002',pre,'Currency projection cannot be evaluated until exact authorized state is established.');const tr=declaredTransformation(f);if(tr)return result('TP-CX-002','UNKNOWN','UNSUPPORTED_PAYMENT_TRANSFORMATION','Declared payment transformation is not modeled.','UNSUPPORTED_TRANSFORMATION',{transformation:tr});const uc=c?.raw?.currency,pc=p?.raw?.payment_amount?.currency;if(!uc||!pc)return result('TP-CX-002','UNKNOWN','CURRENCY_EVIDENCE_MISSING','Checkout or payment currency is missing.','MISSING_EVIDENCE');if(uc!==pc)return result('TP-CX-002','BLOCK','PAYMENT_CURRENCY_MISMATCH',`Approved payment currency ${pc} does not match authorized checkout currency ${uc}.`,null,{authorized_currency:uc,payment_currency:pc});return result('TP-CX-002','PASS','PAYMENT_CURRENCY_MATCH','Approved payment currency matches authorized checkout currency.',null,{currency:uc});}
function totalProjection(f,c,p,pre,currency){if(pre.status!=='PASS')return dependentUnknown('TP-CX-001',pre,'Total projection cannot be evaluated until exact authorized state is established.');const tr=declaredTransformation(f);if(tr)return result('TP-CX-001','UNKNOWN','UNSUPPORTED_PAYMENT_TRANSFORMATION','Declared payment transformation is not modeled.','UNSUPPORTED_TRANSFORMATION',{transformation:tr});if(currency.status==='BLOCK')return result('TP-CX-001','UNKNOWN','CURRENCY_MISMATCH_PREVENTS_AMOUNT_COMPARISON','Amount equality is not meaningful across mismatched currencies.','UNSUPPORTED_TRANSFORMATION');if(currency.status==='UNKNOWN')return result('TP-CX-001','UNKNOWN','CURRENCY_NOT_PROVEN','Amount projection requires comparable currency.',currency.unknown_reason||'MISSING_EVIDENCE');const total=authoritativeTotal(c),amount=p?.raw?.payment_amount?.amount;if(!Number.isInteger(total))return result('TP-CX-001','UNKNOWN','AUTHORITATIVE_TOTAL_MISSING','Authoritative UCP grand total is missing or ambiguous.','MISSING_EVIDENCE');if(!Number.isInteger(amount))return result('TP-CX-001','UNKNOWN','PAYMENT_AMOUNT_MISSING','AP2 approved payment amount is missing.','MISSING_EVIDENCE');if(total!==amount)return result('TP-CX-001','BLOCK','PAYMENT_TOTAL_MISMATCH',`Approved payment amount ${amount} does not match authorized checkout total ${total}.`,null,{authorized_total:total,payment_amount:amount});return result('TP-CX-001','PASS','PAYMENT_TOTAL_MATCH','Approved payment amount matches authorized checkout grand total.',null,{amount:total});}
export function aggregateDecision(results){return results.reduce((b,r)=>PRECEDENCE[r.status]>PRECEDENCE[b]?r.status:b,'PASS');}
export function verifyFixture(fixture){if(!fixture||typeof fixture!=='object')throw new TypeError('fixture must be an object');const c=findObject(fixture,'ucp','checkout'),p=findObject(fixture,'ap2','payment_mandate');const r3=exactState(c,p),r2=currencyProjection(fixture,c,p,r3),r1=totalProjection(fixture,c,p,r3,r2),results=[r3,r2,r1];return {core_schema_version:'m2.1',evaluation_id:`eval:${fixture.fixture_version||'unknown'}`,results,decision:aggregateDecision(results)};}
